import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { UppyProvider } from "@/components/uppy-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("py-10", inter.className)}>
				<main className="flex flex-col max-w-7xl mx-auto">
					<nav className=" divide-x-4">
						<Link href="/uppy">Uppy</Link>
						<Link href="/filepond">Filepond</Link>
						<Link href="/">home</Link>
					</nav>
					{/* make */}
					<UppyProvider>{children}</UppyProvider>
				</main>
			</body>
		</html>
	);
}
